version: "3.9"

services:

  neuroguard:

    build: .

    container_name: neuroguard-api

    ports:
      - "8000:8000"

    restart: unless-stopped

    volumes:
      - ./artifacts:/app/artifacts

    environment:
      - PYTHONUNBUFFERED=1